// ui/src/lib/components/GameCard.svelte
<script lang="ts">
  import type { Game } from "../stores/library";
  import { launchGame, platformLabels } from "../stores/library";

  export let game: Game;

  let launching = false;
  async function onLaunch() {
    launching = true;
    try {
      await launchGame(game);
    } finally {
      launching = false;
    }
  }
</script>

<button class="card hm-focusable" on:click={onLaunch} disabled={launching}>
  <div class="cover">
    {#if game.cover_url}
      <img src={game.cover_url} alt={game.title} loading="lazy" />
    {:else}
      <div class="cover-fallback">{game.title.slice(0, 1)}</div>
    {/if}
    {#if launching}
      <div class="launching-badge">Uruchamianie…</div>
    {/if}
  </div>
  <div class="meta">
    <span class="title">{game.title}</span>
    <span class="platform">{platformLabels[game.platform]}</span>
  </div>
</button>

<style>
  .card {
    display: flex;
    flex-direction: column;
    width: 190px;
    border-radius: var(--radius-md);
    overflow: hidden;
    background: var(--bg-panel-raised);
    text-align: left;
  }
  .cover {
    position: relative;
    width: 100%;
    aspect-ratio: 2 / 3;
    background: var(--bg-panel);
  }
  .cover img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    display: block;
  }
  .cover-fallback {
    width: 100%;
    height: 100%;
    display: grid;
    place-items: center;
    font-size: 42px;
    font-weight: 800;
    color: var(--text-muted);
  }
  .launching-badge {
    position: absolute;
    inset: auto 0 0 0;
    background: rgba(0, 0, 0, 0.7);
    color: var(--accent);
    font-size: 11px;
    font-weight: 700;
    text-align: center;
    padding: 6px 0;
  }
  .meta {
    padding: 10px 12px 12px;
    display: flex;
    flex-direction: column;
    gap: 2px;
  }
  .title {
    font-size: 13px;
    font-weight: 700;
    color: var(--text-primary);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  .platform {
    font-size: 11px;
    color: var(--text-muted);
  }
  .card:hover {
    background: var(--bg-panel-hover);
    transform: translateY(-2px);
  }
</style>

// source-code/frontend/src/components/GameCard.tsx
import { Component, createSignal, onCleanup, onMount, Show } from "solid-js";
import { useNavigate } from "@solidjs/router";
import { api, type Game } from "@/lib/tauri";
import { useFocusable } from "@/lib/focusNav";
import { IconDownload, IconPlay } from "@/components/Icons";

const GameCard: Component<{ game: Game }> = (props) => {
  const navigate = useNavigate();
  const [launching, setLaunching] = createSignal(false);
  const [installing, setInstalling] = createSignal(false);
  const [progressLine, setProgressLine] = createSignal<string | null>(null);
  const [progressPercent, setProgressPercent] = createSignal<number | null>(null);
  const [errorMsg, setErrorMsg] = createSignal<string | null>(null);
  const focusable = useFocusable<HTMLDivElement>(() => (props.game.installed ? launch() : install()));

  onMount(() => {
    const progressUnlisten = api.onInstallProgress((label, line, percent) => {
      if (label.endsWith(`:${props.game.id}`)) {
        setProgressLine(line);
        if (percent !== null) setProgressPercent(percent);
      }
    });
    const finishedUnlisten = api.onInstallFinished((label, ok) => {
      if (label.endsWith(`:${props.game.id}`)) {
        setInstalling(false);
        setProgressLine(null);
        setProgressPercent(null);
        if (!ok) setErrorMsg("Instalacja nie powiodła się.");
      }
    });
    onCleanup(() => {
      void progressUnlisten.then((u) => u());
      void finishedUnlisten.then((u) => u());
    });
  });

  async function launch() {
    setLaunching(true);
    setErrorMsg(null);
    try {
      await api.launchGame(props.game.platform, props.game.id);
    } catch (err) {
      setErrorMsg(String(err));
    } finally {
      setLaunching(false);
    }
  }

  async function install() {
    setInstalling(true);
    setErrorMsg(null);
    try {
      await api.installGame(props.game.platform, props.game.id);
    } catch (err) {
      setErrorMsg(String(err));
      setInstalling(false);
    }
  }

  return (
    <div class="game-card" ref={focusable.ref} tabIndex={0} data-focusable>
      <button class="cover" onClick={() => (props.game.installed ? launch() : install())} disabled={launching() || installing()}>
        {props.game.cover_path ? (
          <img
            src={props.game.cover_path}
            alt={props.game.title}
            style={{ width: "100%", height: "100%", "object-fit": "cover", "border-radius": "10px" }}
          />
        ) : (
          <span>{props.game.title}</span>
        )}
      </button>
      <span class="badge">{props.game.platform}</span>
      <div class="title">{props.game.title}</div>
      <Show when={props.game.playtime_minutes !== null && props.game.playtime_minutes! > 0}>
        <span style={{ "font-size": "11px", color: "var(--text-muted)" }}>
          {Math.round((props.game.playtime_minutes ?? 0) / 6) / 10} godz.
        </span>
      </Show>
      <button
        class="ghost-btn"
        style={{ padding: "4px 10px", "font-size": "11px" }}
        onClick={() => navigate(`/game/${props.game.platform}/${props.game.id}`)}
      >
        ℹ Szczegóły
      </button>

      <Show when={errorMsg()}>
        <div style={{ color: "var(--danger)", "font-size": "11px" }}>{errorMsg()}</div>
      </Show>
      <Show when={progressLine()}>
        <div style={{ color: "var(--text-muted)", "font-size": "10px", "white-space": "nowrap", overflow: "hidden", "text-overflow": "ellipsis" }}>
          {progressLine()}
        </div>
        <Show when={progressPercent() !== null}>
          <div style={{ height: "4px", background: "rgba(255,255,255,0.08)", "border-radius": "999px", overflow: "hidden" }}>
            <div
              style={{
                height: "100%",
                width: `${progressPercent()}%`,
                background: "var(--accent)",
                transition: "width 0.2s",
              }}
            />
          </div>
        </Show>
      </Show>

      <Show
        when={props.game.installed}
        fallback={
          <button class="ghost-btn" onClick={install} disabled={installing()}>
            {installing() ? "Instalowanie…" : <><IconDownload size={14} /> Zainstaluj</>}
          </button>
        }
      >
        <button class="primary-btn" onClick={launch} disabled={launching()}>
          {launching() ? "…" : <><IconPlay size={14} /> Uruchom</>}
        </button>
      </Show>
    </div>
  );
};

export default GameCard;
